default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  username: postgres
  password: meryem99

test:
  <<: *default
  database: budget_app_test
  username: postgres
  password: meryem99

production:
  <<: *default
  database: budget_app_z2ba
  username: budget
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
